-- ===================
-- CREATE TABLES
-- ===================

-- GTFS-style Tables

CREATE TABLE "shapes" (
  "shape_id" varchar(255),
  "shape_pt_lat_lon" point,
  "shape_pt_sequence" int,
  "shape_dist_traveled" decimal(3,1),
  PRIMARY KEY ("shape_id", "shape_pt_sequence")
);

CREATE TABLE "routes" (
  "route_id" varchar(255) PRIMARY KEY,
  "agency_id" varchar(255),
  "route_short_name" varchar(255),
  "route_long_name" text,
  "route_desc" text,
  "route_type" smallint,
  "route_url" text,
  "route_color" text,
  "route_text_color" text,
  "route_sort_order" integer,
  "continous_pickup" smallint,
  "continous_drop_off" smallint,
  "network_id" varchar(255)
);

CREATE TABLE "agency" (
  "agency_id" varchar(255) PRIMARY KEY,
  "agency_name" varchar(255),
  "agency_url" text,
  "agency_timezone" text,
  "agency_lang" char(2),
  "agency_phone" text,
  "agency_fare_url" text,
  "agency_email" text
);

CREATE TABLE "trips" (
  "trip_id" varchar(255) PRIMARY KEY,
  "route_id" varchar(255),
  "service_id" varchar(255),
  "trip_headsign" text,
  "trip_short_name" text,
  "direction_id" smallint,
  "block_id" text,
  "shape_id" varchar(255),
  "wheelchair_accessible" smallint,
  "bikes_allowed" smallint
);

CREATE TABLE "calendar" (
  "service_id" varchar(255) PRIMARY KEY,
  "monday" boolean,
  "tuesday" boolean,
  "wednesday" boolean,
  "thursday" boolean,
  "friday" boolean,
  "saturday" boolean,
  "sunday" boolean,
  "start_date" date,
  "end_date" date
);

CREATE TABLE "calendar_dates" (
  "service_id" varchar(255),
  "date" date,
  "exception_type" smallint,
  PRIMARY KEY ("service_id", "date")
);

CREATE TABLE "frequencies" (
  "trip_id" varchar(255) PRIMARY KEY,
  "start_time" time,
  "end_time" time,
  "headway_secs" int,
  "exact_times" smallint
);

CREATE TABLE "stops" (
  "stop_id" varchar(255) PRIMARY KEY,
  "stop_code" varchar(255),
  "stop_name" text,
  "tts_stop_name" text,
  "stop_desc" text,
  "stop_lat_lon" point,
  "zone_id" varchar(255),
  "stop_url" text,
  "location_type" smallint,
  "parent_station" varchar(255),
  "stop_timezone" text,
  "wheelchair_boarding" smallint,
  "level_id" varchar(255),
  "platform_code" text
);

CREATE TABLE "stop_times" (
  "trip_id" varchar(255),
  "stop_sequence" int,
  "arrival_time" time,
  "departure_time" time,
  "arrival_time_add_days" smallint DEFAULT 0,
  "departure_time_add_days" smallint DEFAULT 0,
  "stop_id" varchar(255),
  "location_group_id" varchar(255),
  "location_id" varchar(255),
  "stop_headsign" text,
  "start_pickup_drop_off_window" time,
  "end_pickup_drop_off_window" time,
  "pickup_type" smallint,
  "drop_off_type" smallint,
  "continous_pickup" smallint,
  "continous_drop_off" smallint,
  "shape_dist_traveled" decimal(3,1),
  "timepoint" smallint,
  "pickup_booking_rule_id" smallint,
  "drop_off_booking_rule_id" smallint,
  PRIMARY KEY ("trip_id", "stop_sequence")
);

-- GTFSRT
CREATE TABLE "vehicle_positions" (
  "oid" varchar(255) PRIMARY KEY,
  "trip_trip_id" varchar(64),
  "trip_route_id" varchar(64),
  "trip_start_time" varchar(8),
  "trip_start_date" varchar(10),
  "stop_id" varchar(255),
  "vehicle_id" varchar(64),
  "vehicle_label" varchar(255),
  "position_latitude" float,
  "position_longitude" float,
  "position_earing" float,
  "position_speed" float,
  "occupancy_status" varchar(27),
  "current_stop_sequence" int,
  "current_status" varchar(80),
  "timestamp" timestamp
);

CREATE TABLE "entity_selectors" (
  "oid" varchar(255) PRIMARY KEY,
  "agency_id" varchar(15),
  "route_id" varchar(64),
  "stop_id" varchar(255),
  "route_type" smallint,
  "trip_id" varchar(64),
  "trip_route_id" varchar(64),
  "trip_start_time" varchar(8),
  "trip_start_date" varchar(10),
  "alert_id" varchar(255)
);

CREATE TABLE "stop_time_updates" (
  "oid" varchar(255) PRIMARY KEY,
  "stop_sequence" int,
  "stop_id" varchar(255),
  "arrival_delay" real,
  "arrival_time" varchar(26),
  "arrival_uncertainty" real,
  "departure_delay" real,
  "departure_time" varchar(26),
  "departure_uncertainty" real,
  "schedule_relationship" varchar(255),
  "trip_update_id" varchar(255)
);

CREATE TABLE "trip_updates" (
  "oid" varchar(255) PRIMARY KEY,
  "trip_id" varchar(64),
  "route_id" varchar(255),
  "start_time" varchar(8),
  "start_date" varchar(10),
  "schedule_relationship" varchar(255),
  "vehicle_id" varchar(64),
  "vehicle_label" varchar(255),
  "vehicle_license_plate" varchar(10),
  "delay" int,
  "timestamp" timestamp
);

CREATE TABLE "alerts" (
  "oid" varchar(255) PRIMARY KEY,
  "active_period" json,
  "cause" varchar(255),
  "effect" varchar(255),
  "url" varchar(300),
  "header_text" varchar(80),
  "description_text" text,
  "severity_level" varchar(80),
  "url_translation" json,
  "header_text_translation" json,
  "description_text_translation" json
);

CREATE TABLE "realtime_source" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "url" text,
  "write" boolean NOT NULL,
  "verbose" boolean NOT NULL,
  "batch_size" smallint NOT NULL DEFAULT 200,
  "active" boolean NOT NULL DEFAULT FALSE,
  "refresh_period" smallint
);

CREATE TABLE "realtime_source_agency" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "realtime_source_id" bigint,
  "agency_id" varchar(255),
  "uuid" UUID NOT NULL DEFAULT gen_random_uuid ()
);

-- Survey Tables
CREATE TABLE "survey_template" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(80),
  "display_title" varchar(80),
  "description" text,
  "type" varchar(80)
);

CREATE TABLE "author" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "first_name" varchar(255),
  "last_name" varchar(255),
  "institution_name" text
);

CREATE TABLE "survey_template_author" (
  "author_id" bigint,
  "survey_template_id" bigint,
  "display_order" int,
  PRIMARY KEY ("author_id", "survey_template_id")
);

CREATE TABLE "template_section" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "survey_template_id" bigint,
  "display_order" int,
  "title" text,
  "description" text,
  "display_next_page" boolean
);

CREATE TABLE "template_question" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "survey_template_id" bigint,
  "text" text,
  "description" text,
  "display_order" int,
  "template_section_id" bigint,
  "answer_format" varchar(80),
  "is_required" boolean DEFAULT FALSE,
  "max_value" smallint,
  "min_value" smallint,
  "select_values" json
);

CREATE TABLE "service_aspect" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(80)
);

CREATE TABLE "service_aspect_formula" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "survey_template_id" bigint NOT NULL,
  "service_aspect_id" bigint NOT NULL,
  "weight" real,
  "formula" text
);

CREATE TABLE "measures_aspect" (
  "template_question_id" bigint,
  "aspect_id" bigint,
  PRIMARY KEY ("template_question_id", "aspect_id")
);

CREATE TABLE "survey" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "survey_template_id" bigint NOT NULL,
  "is_active" boolean NOT NULL DEFAULT FALSE,
  "timestamp" timestamp DEFAULT CURRENT_TIMESTAMP,
  "uuid" UUID NOT NULL DEFAULT gen_random_uuid ()
);

CREATE TABLE "survey_submission" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "survey_id" bigint NOT NULL,
  "route_id" varchar(255),
  "trip_id" varchar(255),
  "ticket_hash" text,
  "timestamp" timestamp DEFAULT CURRENT_TIMESTAMP,
  "uuid" UUID NOT NULL DEFAULT gen_random_uuid ()
);

CREATE TABLE "submitted_answer" (
  "id" bigint PRIMARY KEY UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "submission_id" bigint NOT NULL,
  "template_question_id" bigint NOT NULL,
  "value" text,
  "uuid" UUID NOT NULL DEFAULT gen_random_uuid ()
);

-- ===================
-- ALTER TABLES: ADD FOREIGN KEYS AND CONSTRAINTS
-- ===================

-- GTFS Alterations

ALTER TABLE "shapes"
  ADD CONSTRAINT "UQ_shapes_shape_id" UNIQUE ("shape_id","shape_pt_sequence");

ALTER TABLE "trips"
  ADD FOREIGN KEY ("route_id") REFERENCES "routes"("route_id"),
  ADD FOREIGN KEY ("service_id") REFERENCES "calendar"("service_id");

ALTER TABLE "vehicle_positions"
  ADD FOREIGN KEY ("trip_trip_id") REFERENCES "trips"("trip_id"),
  ADD FOREIGN KEY ("route_id") REFERENCES "routes"("route_id");

ALTER TABLE "stop_times"
  ADD FOREIGN KEY ("trip_id") REFERENCES "trips"("trip_id"),
  ADD FOREIGN KEY ("stop_id") REFERENCES "stops"("stop_id");

ALTER TABLE "routes"
  ADD FOREIGN KEY ("agency_id") REFERENCES "agency"("agency_id");

ALTER TABLE "stops"
  ADD FOREIGN KEY ("parent_station") REFERENCES "stops"("stop_id");

ALTER TABLE "stop_time_updates"
  ADD FOREIGN KEY ("stop_id") REFERENCES "stops"("stop_id"),
  ADD FOREIGN KEY ("trip_update_id") REFERENCES "trip_updates"("oid");

ALTER TABLE "trip_updates"
  ADD FOREIGN KEY ("trip_id") REFERENCES "trips"("trip_id");

ALTER TABLE "calendar_dates"
  ADD FOREIGN KEY ("service_id") REFERENCES "calendar"("service_id");

ALTER TABLE "frequencies"
  ADD FOREIGN KEY ("trip_id") REFERENCES "trips"("trip_id");

ALTER TABLE "entity_selectors"
  ADD FOREIGN KEY ("agency_id") REFERENCES "agency"("agency_id"),
  ADD FOREIGN KEY ("alert_id") REFERENCES "alerts"("oid"),
  ADD FOREIGN KEY ("route_id") REFERENCES "routes"("route_id"),
  ADD FOREIGN KEY ("stop_id") REFERENCES "stops"("stop_id"),
  ADD FOREIGN KEY ("trip_id") REFERENCES "trips"("trip_id");

ALTER TABLE "alerts"
  ADD CONSTRAINT "UQ_alerts_oid" UNIQUE ("oid");

ALTER TABLE "realtime_source_agency"
  ADD FOREIGN KEY ("agency_id") REFERENCES "agency"("agency_id"),
  ADD FOREIGN KEY ("realtime_source_id") REFERENCES "realtime_source"("id");

-- Survey Alterations
ALTER TABLE "survey_template_author"
  ADD FOREIGN KEY ("author_id") REFERENCES "author"("id"),
  ADD FOREIGN KEY ("survey_template_id") REFERENCES "survey_template"("id");

ALTER TABLE "template_section"
  ADD FOREIGN KEY ("survey_template_id") REFERENCES "survey_template"("id");

ALTER TABLE "template_question"
  ADD FOREIGN KEY ("survey_template_id") REFERENCES "survey_template"("id"),
  ADD FOREIGN KEY ("template_section_id") REFERENCES "template_section"("id");

ALTER TABLE "service_aspect_formula"
  ADD FOREIGN KEY ("survey_template_id") REFERENCES "survey_template"("id"),
  ADD FOREIGN KEY ("service_aspect_id") REFERENCES "service_aspect"("id");

ALTER TABLE "measures_aspect"
  ADD FOREIGN KEY ("template_question_id") REFERENCES "template_question"("id"),
  ADD FOREIGN KEY ("aspect_id") REFERENCES "service_aspect"("id");

ALTER TABLE "survey"
  ADD FOREIGN KEY ("survey_template_id") REFERENCES "survey_template"("id");

ALTER TABLE "survey_submission"
  ADD FOREIGN KEY ("survey_id") REFERENCES "survey"("id"),
  ADD FOREIGN KEY ("route_id") REFERENCES "routes"("route_id"),
  ADD FOREIGN KEY ("trip_id") REFERENCES "trips"("trip_id");

ALTER TABLE "submitted_answer"
  ADD FOREIGN KEY ("template_question_id") REFERENCES "template_question"("id"),
  ADD FOREIGN KEY ("submission_id") REFERENCES "survey_submission"("id");

-- ===================
-- VIEWS SETUP
-- ===================

CREATE OR REPLACE VIEW agency_summary_view AS
SELECT
    a.agency_id,
    a.agency_name,
    a.agency_url,
    a.agency_timezone,
    COUNT(DISTINCT r.route_id) AS route_count,
    COUNT(DISTINCT t.trip_id) AS trip_count
FROM
    agency a
LEFT JOIN routes r ON r.agency_id = a.agency_id
LEFT JOIN trips t ON t.route_id = r.route_id
GROUP BY
    a.agency_id, a.agency_name, a.agency_url, a.agency_timezone;

-- ===================
-- TRIGGER SETUP
-- ===================
CREATE OR REPLACE FUNCTION survey_submission_set_route_id()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    -- Run only when a trip_id was supplied and route_id is still empty
    IF NEW.trip_id IS NOT NULL
       AND NEW.route_id IS NULL THEN
       
       -- Copy the route_id from trips into the just-inserted row
       UPDATE survey_submission ss
       SET    route_id = t.route_id
       FROM   trips t
       WHERE  t.trip_id = NEW.trip_id
         AND  ss.id     = NEW.id;   -- lock onto the same row
    END IF;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_survey_submission_set_route_id ON survey_submission;

CREATE TRIGGER trg_survey_submission_set_route_id
AFTER INSERT ON survey_submission
FOR EACH ROW
EXECUTE FUNCTION survey_submission_set_route_id();

-- ===================
-- POSTGREST SETUP
-- ===================

CREATE ROLE authenticator LOGIN NOINHERIT NOCREATEDB NOCREATEROLE NOSUPERUSER;
CREATE ROLE anonymous NOLOGIN;
CREATE ROLE webuser NOLOGIN;

-- ===================
-- CREATE ROLES
-- ===================

GRANT USAGE ON SCHEMA public TO anonymous;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anonymous;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO anonymous;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO anonymous;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO anonymous;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anonymous;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anonymous;
GRANT anonymous TO authenticator;

-- ===================
-- INSERT SURVEY PRESETS
-- ===================

INSERT INTO author (first_name, last_name, institution_name) VALUES
  ('Laura','Eboli','University of Calabria'),
  ('Gabriella','Mazzulla','University of Calabria'),
  ('A Parsu','Parasuraman','University of Miami'),
  ('Valarie','Zeithaml','University of North Carolina at Chapel Hill'),
  ('Leonard','Berry','Texas A&M University');

INSERT INTO survey_template (title, display_title, description, type) VALUES
  ('Parasuraman et al. (1988)', 'Service Quality Assessment','', 'SERVQUAL'),
  ('Eboli and Mazzulla (2015)', 'Eboli and Mazzulla (2015)','doi:10.1007/s12469-014-0096-x','SERVQUAL');

INSERT INTO survey_template_author (author_id, survey_template_id, display_order) VALUES
  ((SELECT id FROM AUTHOR WHERE first_name='Laura' AND last_name='Eboli' LIMIT 1), (SELECT id FROM survey_template WHERE title='Eboli and Mazzulla (2015)' LIMIT 1), 0),
  ((SELECT id FROM AUTHOR WHERE first_name='Gabriella' AND last_name='Mazzulla' LIMIT 1), (SELECT id FROM survey_template WHERE title='Eboli and Mazzulla (2015)' LIMIT 1), 10),
  ((SELECT id FROM AUTHOR WHERE first_name='A Parsu' AND last_name='Parasuraman' LIMIT 1), (SELECT id FROM survey_template WHERE title='Parasuraman et al. (1988)' LIMIT 1), 0),
  ((SELECT id FROM AUTHOR WHERE first_name='Valarie' AND last_name='Zeithaml' LIMIT 1), (SELECT id FROM survey_template WHERE title='Parasuraman et al. (1988)' LIMIT 1), 10),
  ((SELECT id FROM AUTHOR WHERE first_name='Leonard' AND last_name='Berry' LIMIT 1), (SELECT id FROM survey_template WHERE title='Parasuraman et al. (1988)' LIMIT 1), 10);

-- ===================
-- INSERT SURVEY TEMPLATE QUESTIONS Parasuraman et al. (1988)
-- ===================

INSERT INTO template_question
        (survey_template_id, "text", description, display_order,
         template_section_id, answer_format, is_required,
         max_value, min_value, select_values)
VALUES
-- ───────────── EXPECTATIONS ─────────────
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'They should have up-to-date equipment.',                          NULL,  10, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Their physical facilities should be visually appealing.',          NULL,  20, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Their employees should be well dressed and appear neat.',          NULL,  30, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'The appearance of physical facilities of these firms should be in keeping with the type of services provided.',
                                                                     NULL,  40, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'When these firms promise to do something by certain time, they should do so.',
                                                                     NULL,  50, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'When customers have problems, these firms should be sympathetic and reassuring.',
                                                                     NULL,  60, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'These firms should be dependable.',                               NULL,  70, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'They should provide their services at the time they promise to do so.',
                                                                     NULL,  80, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'They should keep their records accurately.',                      NULL,  90, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'They shouldn''t be expected to tell customers exactly when services will be performed.',
                                                                     NULL, 100, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'It is not realistic for customers to expect prompt service from employees of these firms.',
                                                                     NULL, 110, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Their employees don''t always have to be willing to help customers.',
                                                                     NULL, 120, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'It is okay if they are too busy to respond to customer requests promptly.',
                                                                     NULL, 130, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Customers should be able to feel safe in their transactions with these firms'' employees.',
                                                                     NULL, 140, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Their employees should be polite.',                               NULL, 150, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Their employees should get adequate support from these firms to do their jobs.',
                                                                     NULL, 160, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Their employees should get adequate support from these firms to do their jobs well.',
                                                                     NULL, 170, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'These firms should not be expected to give customers personal attention.',
                                                                     NULL, 180, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Employees of these firms cannot be expected to give customers personal attention.',
                                                                     NULL, 190, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'It is unrealistic to expect employees to know what the needs of their customers are.',
                                                                     NULL, 200, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'It is unrealistic to expect these firms to have their customers'' best interests at heart.',
                                                                     NULL, 210, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'They shouldn''t be expected to have operating hours convenient to their customers.',
                                                                     NULL, 220, NULL, 'number', TRUE, 7, 0, NULL),

-- ───────────── PERCEPTIONS ─────────────
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ has up-to-date equipment.',                                    NULL, 230, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ''s physical facilities are visually appealing.',               NULL, 240, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ''s employees are well dressed and appear neat.',               NULL, 250, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'The appearance of physical facilities of XYZ is in keeping with the type of services provided.',
                                                                     NULL, 260, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'When XYZ promises to do something by certain time, it does so.',   NULL, 270, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'When customers have problems, XYZ is sympathetic and reassuring.', NULL, 280, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ is dependable.',                                               NULL, 290, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ provides its services at the time it promises to do so.',      NULL, 300, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ keeps its records accurately.',                                NULL, 310, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ doesn''t tell customers exactly when services will be performed.',
                                                                     NULL, 320, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'You do not receive prompt service from XYZ''s employees.',         NULL, 330, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Employees of XYZ don''t always have to be willing to help customers.',
                                                                     NULL, 340, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Employees of XYZ are too busy to respond to customer requests promptly.',
                                                                     NULL, 350, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'You can trust employees of XYZ.',                                  NULL, 360, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'You feel safe in your transactions with XYZ''s employees.',        NULL, 370, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Employees of XYZ are polite.',                                     NULL, 380, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Employees get adequate support from XYZ to do their jobs well.',   NULL, 390, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ does not give you personal attention.',                        NULL, 400, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Employees of XYZ do not give you personal attention.',             NULL, 410, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'Employees of XYZ do not know what your needs are.',                NULL, 420, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ does not have your best interests at heart.',                  NULL, 430, NULL, 'number', TRUE, 7, 0, NULL),
((SELECT id FROM survey_template WHERE title = 'Parasuraman et al. (1988)' LIMIT 1),
 'XYZ does not have operating hours convenient to all its customers.', 
                                                                     NULL, 440, NULL, 'number', TRUE, 7, 0, NULL);

-- ===================
-- INSERT SURVEY TEMPLATE QUESTIONS Eboli and Mazzulla (2015)
-- ===================

INSERT INTO template_question
        (survey_template_id, "text", description, display_order,
         template_section_id, answer_format, is_required,
         max_value, min_value, select_values)
VALUES
/* ──────────────── IMPORTANCE (I1-I33) ──────────────── */
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Travel safety (1–10).',                   NULL,  10, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Personal security on board (1–10).',      NULL,  20, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Personal security at station (1–10).',    NULL,  30, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Cleanliness of vehicles (1–10).',         NULL,  40, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Cleanliness of seats (1–10).',            NULL,  50, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Maintenance of seats (1–10).',            NULL,  60, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Cleanliness of toilet facilities (1–10).',NULL,  70, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Cleanliness of stations (1–10).',         NULL,  80, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Maintenance of stations (1–10).',         NULL,  90, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Crowding on board (1–10).',               NULL, 100, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Air-conditioning on board (1–10).',       NULL, 110, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Comfort on board (1–10).',                NULL, 120, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Fare/service ratio (1–10).',              NULL, 130, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Frequency of runs (1–10).',               NULL, 140, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Punctuality of runs (1–10).',             NULL, 150, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Regularity of runs (1–10).',              NULL, 160, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Integration with PT (1–10).',             NULL, 170, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Localization of Stations (1–10).',        NULL, 180, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Parking (1–10).',                         NULL, 190, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Bicycle transport on board (1–10).',      NULL, 200, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Facilities for the disabled (1–10).',     NULL, 210, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Substitute services (1–10).',             NULL, 220, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Information at stations (1–10).',         NULL, 230, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Information on board (1–10).',            NULL, 240, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Info timeliness at stations (1–10).',     NULL, 250, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Info timeliness on board (1–10).',        NULL, 260, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Complaints handling (1–10).',             NULL, 270, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Communication to office (1–10).',         NULL, 280, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Info connections with PT (1–10).',        NULL, 290, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Kindness on board (1–10).',               NULL, 300, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Competence on board (1–10).',             NULL, 310, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Ticket inspection (1–10).',               NULL, 320, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate the importance of Kindness at station (1–10).',             NULL, 330, NULL, 'number', TRUE, 10, 1, NULL),

/* ──────────────── SATISFACTION (S1-S33) ──────────────── */
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Travel safety (1–10).',              NULL, 410, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Personal security on board (1–10).', NULL, 420, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Personal security at station (1–10).',NULL, 430, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Cleanliness of vehicles (1–10).',    NULL, 440, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Cleanliness of seats (1–10).',       NULL, 450, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Maintenance of seats (1–10).',       NULL, 460, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Cleanliness of toilet facilities (1–10).',NULL, 470, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Cleanliness of stations (1–10).',    NULL, 480, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Maintenance of stations (1–10).',    NULL, 490, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Crowding on board (1–10).',          NULL, 500, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Air-conditioning on board (1–10).',  NULL, 510, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Comfort on board (1–10).',           NULL, 520, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Fare/service ratio (1–10).',         NULL, 530, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Frequency of runs (1–10).',          NULL, 540, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Punctuality of runs (1–10).',        NULL, 550, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Regularity of runs (1–10).',         NULL, 560, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Integration with PT (1–10).',        NULL, 570, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Localization of Stations (1–10).',   NULL, 580, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Parking (1–10).',                    NULL, 590, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Bicycle transport on board (1–10).', NULL, 600, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Facilities for the disabled (1–10).',NULL, 610, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Substitute services (1–10).',        NULL, 620, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Information at stations (1–10).',    NULL, 630, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Information on board (1–10).',       NULL, 640, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Info timeliness at stations (1–10).',NULL, 650, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Info timeliness on board (1–10).',   NULL, 660, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Complaints handling (1–10).',        NULL, 670, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Communication to office (1–10).',    NULL, 680, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Info connections with PT (1–10).',   NULL, 690, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Kindness on board (1–10).',          NULL, 700, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Competence on board (1–10).',        NULL, 710, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Ticket inspection (1–10).',          NULL, 720, NULL, 'number', TRUE, 10, 1, NULL),
((SELECT id FROM survey_template WHERE title = 'Eboli and Mazzulla (2015)' LIMIT 1),
 'Rate your satisfaction with Kindness at station (1–10).',        NULL, 730, NULL, 'number', TRUE, 10, 1, NULL);